### ISSUE TITLE
segfault if concurrency > number of games

### ISSUE THREAD

**Issue by vondele** [lucasart/c-chess-cli#37]
-games 2 -rounds 1 -concurrency 14

```
Thread 8 "c-chess-cli" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4927700 (LWP 75118)]
0x000055555555a559 in str_ref (src=src@entry=0x0) at src/str.c:82
82	    const size_t len = strlen(src);
(gdb) bt
#0  0x000055555555a559 in str_ref (src=src@entry=0x0) at src/str.c:82
#1  0x0000555555561701 in deadline_set (w=w@entry=0x55555564ffb0, engineName=0x0, timeLimit=21730628) at src/workers.c:29
#2  0x000055555555bf73 in engine_destroy (w=0x55555564ffb0, e=0x7ffff4926df0) at src/engine.c:182
#3  0x000055555555f496 in thread_start (arg=0x55555564ffb0) at src/main.c:162
#4  0x00007ffff7f85609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5d293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by lucasart** [comment]
thanks. fixed a9f957f5a289f55cac4b54a67f44121c4cbf7b45.
